### ISSUE TITLE
Reduce precision for small amounts, confusion due to exponential notation

### ISSUE THREAD

**Issue by secretshardul** [project-serum/swap#4]
The current SRM to HOLD rate is 1 SRM = 42513513.513513513 HOLD.

When I pick HOLD -> SRM and set HOLD amount as 1, it shows that I will receive 2.337826453243471e SRM. This appears as 2.33 on the UI.

![image](https://user-images.githubusercontent.com/49580849/119450870-2e7f6180-bd52-11eb-9b5f-ce77fc03c94b.png)

**Comment by armaniferrante** [comment]
Moving this to the appropriate repo, here https://github.com/project-serum/swap-ui/issues/24.
